name: continuous-integration
on: [push, pull_request]

jobs:
  linux-os:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest  
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          repository: ennorehling/clibs
      - name: Build and Test
        uses: threeal/cmake-action@v1.1.0
        with:
          args: "-DCMAKE_BUILD_TYPE=Release"
          run-test: true
          test-args: "--output-on-failure"

