name: continuous-integration
on: [push, pull_request]

jobs:
  linux-os:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest  
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          repository: ennorehling/clibs
      - name: Build and Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Release
          run-test: true
          ctest-options: --output-on-failure

